# Generated by Django 2.0.4 on 2018-07-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidatures_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatures',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='candidatures',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='candidatures',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Estudante'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='answer_date',
            field=models.DateField(verbose_name='Data de Retorno'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='available',
            field=models.BooleanField(verbose_name='Inscrições Disponíveis'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='benefits',
            field=models.CharField(max_length=255, verbose_name='Benefícios'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='end_at',
            field=models.DateField(verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Vaga'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(max_length=500, verbose_name='Requisitos'),
        ),
    ]
