# Generated by Django 2.0.4 on 2018-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180714_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatures',
            options={'ordering': ('created_at',), 'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ('name',), 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
    ]
