# Generated by Django 2.0.4 on 2018-07-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '__latest__'),
        ('jobs', '0003_auto_20180714_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatures',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='students.Student'),
        ),
    ]
