# Generated by Django 2.0.4 on 2018-07-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180714_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatures',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companies'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companies'),
        ),
    ]
