# Generated by Django 2.0.4 on 2018-06-24 23:40

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=20)),
                ('registration', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.PositiveIntegerField(max_length=14, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=20)),
                ('registration', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('birth_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=20)),
                ('registration', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.CharField(choices=[('SI', 'Sistemas de Informação'), ('CC', 'Ciêncida da Computação'), ('SC', ' Tecnólogo em Sistemas de Computação')], default='SI', max_length=2)),
                ('mini_bio', models.CharField(max_length=600)),
                ('cpf', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('birth_date', models.DateTimeField()),
                ('resume', models.FileField(upload_to='curriculos/')),
                ('allowed', models.BooleanField(default=False)),
                ('competences', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
