# Generated by Django 2.0.4 on 2018-06-24 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999999)]),
        ),
    ]
