# Generated by Django 2.0.4 on 2018-06-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180624_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
