# Generated by Django 2.0.4 on 2018-06-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180624_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='coordinator',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='ChangeMe', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, upload_to='curriculos/'),
        ),
    ]
