# Generated by Django 2.0.4 on 2018-06-25 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180624_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$')]),
        ),
    ]
