# Generated by Django 2.0.4 on 2018-07-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180625_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='birth_date',
        ),
    ]
