# Generated by Django 2.0.4 on 2018-07-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180714_2059'),
        ('users', '0007_remove_coordinator_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='competences',
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
