# Generated by Django 2.0.4 on 2018-07-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180714_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
