# Generated by Django 2.0.4 on 2018-07-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180714_2140'),
        ('users', '0009_delete_coordinator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
