# Generated by Django 2.0.4 on 2018-07-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='register',
            field=models.CharField(max_length=11, verbose_name='Matrícula'),
        ),
    ]
