# Generated by Django 2.0.4 on 2018-07-14 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('registration', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$')], verbose_name='CNPJ')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('approved', models.BooleanField(verbose_name='Cadastro aprovado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ('name',),
            },
        ),
    ]
