# Generated by Django 2.0.4 on 2018-07-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180714_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Cadastro aprovado'),
        ),
    ]
